version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactionsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  transactionservice.api:
    build:
      context: .
      dockerfile: TransactionService.Api/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=transactionsdb;Username=postgres;Password=postgres
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:80"

volumes:
  db_data: